import Head from "next/head";
import Navbar from "../../molecules/Navbar";


const Layout = ({ children }:any) => {
    return (
    <>
        <Head>
            <title>Assessment Test</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="layout">
        <Navbar />
        <div className="layout__content">{children}</div>
        </div>
    </>
    );
};

export default Layout;